{
    DTRACE_NET_SERVER_CONNECTION: [Function],
    DTRACE_NET_STREAM_END: [Function],
    DTRACE_NET_SOCKET_READ: [Function],
    DTRACE_NET_SOCKET_WRITE: [Function],
    DTRACE_HTTP_SERVER_REQUEST: [Function],
    DTRACE_HTTP_SERVER_RESPONSE: [Function],
    DTRACE_HTTP_CLIENT_REQUEST: [Function],
    DTRACE_HTTP_CLIENT_RESPONSE: [Function],
    COUNTER_NET_SERVER_CONNECTION: [Function],
    COUNTER_NET_SERVER_CONNECTION_CLOSE: [Function],
    COUNTER_HTTP_SERVER_REQUEST: [Function],
    COUNTER_HTTP_SERVER_RESPONSE: [Function],
    COUNTER_HTTP_CLIENT_REQUEST: [Function],
    COUNTER_HTTP_CLIENT_RESPONSE: [Function],
    global: [Circular],
    process: {
        title: 'C:\\Program Files (x86)\\Brackets\\node.exe',
        version: 'v0.11.14-nightly-20140819-pre',
        moduleLoadList: ['Binding contextify',
        'Binding natives',
        'NativeModule events',
        'NativeModule util',
        'NativeModule tracing',
        'Binding v8',
        'NativeModule buffer',
        'Binding buffer',
        'Binding smalloc',
        'NativeModule path',
        'NativeModule module',
        'NativeModule vm',
        'NativeModule assert',
        'NativeModule fs',
        'Binding fs',
        'Binding constants',
        'NativeModule stream',
        'NativeModule _stream_readable',
        'NativeModule _stream_writable',
        'NativeModule _stream_duplex',
        'NativeModule _stream_transform',
        'NativeModule _stream_passthrough',
        'NativeModule smalloc',
        'NativeModule crypto',
        'Binding crypto',
        'NativeModule constants',
        'NativeModule string_decoder',
        'NativeModule net',
        'NativeModule timers',
        'Binding timer_wrap',
        'NativeModule _linklist',
        'Binding cares_wrap',
        'Binding uv',
        'Binding pipe_wrap',
        'NativeModule tls',
        'NativeModule url',
        'NativeModule punycode',
        'NativeModule querystring',
        'NativeModule _tls_common',
        'NativeModule _tls_wrap',
        'Binding tls_wrap',
        'NativeModule console',
        'Binding tty_wrap'],
        versions: {
            http_parser: '2.3',
            node: '0.11.14-nightly-20140819-pre',
            v8: '3.26.33',
            uv: '0.11.28',
            zlib: '1.2.3',
            modules: '14',
            openssl: '1.0.1i'
        },
        arch: 'x64',
        platform: 'win32',
        argv: ['node', 'D:\\workspace\\learnNode\\n2Mvc\\common\\basedao.js'],
        execArgv: [],
        env: {
            ALLUSERSPROFILE: 'C:\\ProgramData',
            APPDATA: 'C:\\Users\\yinjie\\AppData\\Roaming',
            CHROME_ALLOCATOR: 'TCMALLOC',
            CommonProgramFiles: 'C:\\Program Files\\Common Files',
            'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
            CommonProgramW6432: 'C:\\Program Files\\Common Files',
            COMPUTERNAME: 'YINJ2014',
            ComSpec: 'C:\\windows\\system32\\cmd.exe',
            FP_NO_HOST_CHECK: 'NO',
            HOMEDRIVE: 'C:',
            HOMEPATH: '\\Users\\yinjie',
            JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.7.0_67',
            LOCALAPPDATA: 'C:\\Users\\yinjie\\AppData\\Local',
            LOGONSERVER: '\\\\UFTDC',
            NLS_LANG: 'SIMPLIFIED CHINESE_CHINA.ZHS16GBK',
            NUMBER_OF_PROCESSORS: '4',
            OS: 'Windows_NT',
            Path: 'C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\3.0\\bin\\x86;C:\\Program Files (x86)\\Intel\\OpenCL SDK\\3.0\\bin\\x64;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files (x86)\\Oracle\\Instant Client\\bin;C:\\Program Files (x86)\\Java\\jdk1.7.0_67\\bin;C:\\Program Files (x86)\\php 5.4.25;C:\\Program Files\\nodejs\\;C:\\Users\\yinjie\\AppData\\Roaming\\npm',
            PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
            PROCESSOR_ARCHITECTURE: 'AMD64',
            PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
            PROCESSOR_LEVEL: '6',
            PROCESSOR_REVISION: '3c03',
            ProgramData: 'C:\\ProgramData',
            ProgramFiles: 'C:\\Program Files',
            'ProgramFiles(x86)': 'C:\\Program Files (x86)',
            ProgramW6432: 'C:\\Program Files',
            PROMPT: '$P$G',
            PSModulePath: 'C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
            PUBLIC: 'C:\\Users\\Public',
            SESSIONNAME: 'Console',
            SystemDrive: 'C:',
            SystemRoot: 'C:\\windows',
            TEMP: 'C:\\Users\\yinjie\\AppData\\Local\\Temp',
            TMP: 'C:\\Users\\yinjie\\AppData\\Local\\Temp',
            TNS_ADMIN: 'C:\\Program Files (x86)\\Oracle\\Instant Client\\network\\admin',
            USERDNSDOMAIN: 'UFSOFT.COM.CN',
            USERDOMAIN: 'PDOMAIN',
            USERNAME: 'yinjie',
            USERPROFILE: 'C:\\Users\\yinjie',
            windir: 'C:\\windows',
            windows_tracing_flags: '3',
            windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log'
        },
        pid: 7864,
        features: {
            debug: false,
            uv: true,
            ipv6: true,
            tls_npn: true,
            tls_sni: true,
            tls_ocsp: true,
            tls: true
        },
        _needImmediateCallback: false,
        execPath: 'C:\\Program Files\\nodejs\\node.exe',
        debugPort: 5858,
        _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
        _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
        _getActiveRequests: [Function: _getActiveRequests],
        _getActiveHandles: [Function: _getActiveHandles],
        reallyExit: [Function: reallyExit],
        abort: [Function: abort],
        chdir: [Function: chdir],
        cwd: [Function: cwd],
        umask: [Function: umask],
        _kill: [Function: _kill],
        _debugProcess: [Function: _debugProcess],
        _debugPause: [Function: _debugPause],
        _debugEnd: [Function: _debugEnd],
        hrtime: [Function: hrtime],
        dlopen: [Function: dlopen],
        uptime: [Function: uptime],
        memoryUsage: [Function: memoryUsage],
        binding: [Function: binding],
        _setupDomainUse: [Function: _setupDomainUse],
        _events: {},
        _rawDebug: [Function],
        domain: null,
        _maxListeners: undefined,
        EventEmitter: {
            [Function: EventEmitter]
            EventEmitter: [Circular],
            usingDomains: false,
            defaultMaxListeners: 10,
            init: [Function],
            listenerCount: [Function]
        },
        _fatalException: [Function],
        _exiting: false,
        assert: [Function],
        config: {
            target_defaults: [Object],
            variables: [Object]
        },
        nextTick: [Function: nextTick],
        _tickCallback: [Function: _tickCallback],
        _tickDomainCallback: [Function: _tickDomainCallback],
        stdout: [Getter],
        stderr: [Getter],
        stdin: [Getter],
        openStdin: [Function],
        exitCode: 0,
        exit: [Function],
        kill: [Function],
        addListener: [Function],
        on: [Function],
        removeListener: [Function],
        mainModule: {
            id: '.',
            exports: [Object],
            parent: null,
            filename: 'D:\\workspace\\learnNode\\n2Mvc\\common\\basedao.js',
            loaded: false,
            children: [Object],
            paths: [Object]
        }
    },
    GLOBAL: [Circular],
    root: [Circular],
    Buffer: {
        [Function: Buffer]
        poolSize: 8192,
        isBuffer: [Function: isBuffer],
        compare: [Function: compare],
        isEncoding: [Function],
        concat: [Function],
        byteLength: [Function]
    },
    setTimeout: [Function],
    setInterval: [Function],
    clearTimeout: [Function],
    clearInterval: [Function],
    setImmediate: [Function],
    clearImmediate: [Function],
    console: [Getter]
}
mysql database connect success!{
    [Error: ER_DUP_ENTRY: Duplicate entry '1004'
        for key 'uq']
    stack: 'Error: ER_DUP_ENTRY: Duplicate entry \'1004\' for key \'uq\'\n    at Query.Sequence._packetToError (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:48:14)\n    at Query.ErrorPacket (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:82:18)\n    at Protocol._parsePacket (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Protocol.js:271:23)\n    at Parser.write (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Parser.js:77:12)\n    at Protocol.write (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Protocol.js:39:16)\n    at Socket.<anonymous> (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\Connection.js:82:28)\n    at Socket.emit (events.js:107:17)\n    at readableAddChunk (_stream_readable.js:158:16)\n    at Socket.Readable.push (_stream_readable.js:125:10)\n    at TCP.onread (net.js:514:20)\n    --------------------\n    at Protocol._enqueue (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Protocol.js:135:48)\n    at PoolConnection.Connection.query (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\Connection.js:185:25)\n    at D:\\workspace\\learnNode\\n2Mvc\\node_modules\\datasource.js:42:24\n    at Handshake.onConnect (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\Pool.js:59:7)\n    at Handshake.Sequence.end (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:96:24)\n    at Handshake.Sequence.OkPacket (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:105:8)\n    at Protocol._parsePacket (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Protocol.js:271:23)\n    at Parser.write (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Parser.js:77:12)\n    at Protocol.write (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\protocol\\Protocol.js:39:16)\n    at Socket.<anonymous> (D:\\workspace\\learnNode\\n2Mvc\\node_modules\\mysql\\lib\\Connection.js:82:28)',
    code: 'ER_DUP_ENTRY',
    errno: 1062,
    sqlState: '23000',
    index: 0
}
undefined